name: Release and Publish

on:
  push:
    branches:
      - master
      - alpha
      - beta
      - next

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Lint Files
        run: npm run lint:check

      - name: Check File Formatting
        run: npm run format:check

      - name: Run Tests
        run: npm run test:ci

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
