name: Run Lint and Tests

on:
  push:
    branches-ignore:
      - main
      - alpha
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Lint Files
        run: npm run lint:check

      - name: Check File Formatting
        run: npm run format:check

      - name: Run Tests
        run: npm run test:ci
